---
title: "Clean Patient Table"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: true
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    # css: custom-css.css
  word_document:
    reference_docx: word_style_template_01.docx
---

# Load packages

```{r load_packages, message=FALSE}
# Cran
library(tidyverse)

# GitHub
# devtools::install_github("mbcann01/dataclean")
library(dataclean)
```

# Load patient table

```{r}
patient <- read_rds(path = "../data/Patient.RData")
```

# Coerce variable types

```{r}
# Transfor dob to age
patient <- patient %>% 
  mutate(
    Created                            = as.POSIXct(Created),
    DateOfBirth                        = as.Date(DateOfBirth),
    UnableToReachOn                    = as.POSIXct(UnableToReachOn),
    LastPhaseReview                    = as.POSIXct(LastPhaseReview),
    LastERHospitalizationDischargeDate = as.POSIXct(LastERHospitalizationDischargeDate),
    LastHospitalizationAdmissionDate   = as.POSIXct(LastHospitalizationAdmissionDate)
  )
```

# Merge with lookup tables

```{r}
# Need to import these on PC
```


# Codebook

```{r}
labels <- c(
  "Patient Id",
  "",
  "Name of staff that created patient record entry",
  "Date patient record entry was created",
  "",
  "",
  "Patient date of birth",
  "Patient gender",
  "Patient city",
  "Patient state",
  "Patient zip code",
  "",
  "Patient marital status",
  "Patient race",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ""
)

codebook(patient, label = labels)
```




-------------------------------------------------------------------------------

&nbsp;

#### Session Info:
```{r session_info, echo=FALSE}
sessionInfo()
```